apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: s01lab06.sulamerica.br
    path: /var/export/nexus
