apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-etc
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: master.devops.org
    path: /var/export/gitlab-etc
