apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-opt
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: s01lab06.sulamerica.br
    path: /var/export/gitlab-opt
