apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-opt
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: master.devops.org
    path: /var/export/gitlab-opt
