apiVersion: v1
kind: PersistentVolume
metadata:
  name: gogs-mysql
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: master.devops.org
    path: /var/export/gogs-mysql 
