apiVersion: v1
kind: Service
metadata: 
  labels: 
    name: gogs
  name: gogs
spec: 
  ports:
    # the port that this service should serve on
    - port: 3000
      targetPort: gogs
  # label keys and values that must match in order to receive traffic for this service
  selector: 
    name: gogs
  type: LoadBalancer
